apiVersion: v1
kind: Service
metadata:
  namespace: proxy
  annotations:
    kompose.cmd: kompose convert -f tester-compose.yaml
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-ssl-proxy
  name: nginx-ssl-proxy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: nginx-ssl-proxy
  type: LoadBalancer
  loadBalancerIP: 104.197.25.108
status:
  loadBalancer: {}
