apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-db-prod
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  portworxVolume:
    volumeID: wp-db-prod
