apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-stage
  namespace: wp
  labels:
    app: wordpress-stage
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-stage
    tier: mysql
  # clusterIP: None
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-stage
  namespace: wp
  labels:
    app: wordpress-stage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: wp
  labels:
    app: wordpress-stage
spec:
  selector:
    matchLabels:
      app: wordpress-stage
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-stage
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql-stage
        volumeMounts:
        - name: mysql-persistent-storage-stage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-stage
        persistentVolumeClaim:
          claimName: mysql-pv-claim-stage
