# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: shared-pvc-wp-sql
#   namespace: wp
#   annotations:
#     volume.beta.kubernetes.io/storage-class: px-shared-sc
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 40Gi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: wp
#   name: mysql
#   labels:
#     app: mysql
# spec:
#   type: ClusterIP
#   ports:
#     - port: 3306
#   selector:
#     app: mysql
# ---
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   namespace: wp
#   name: mysql
#   labels:
#     app: mysql
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#         - image: mysql:5.6
#           name: mysql
#           env:
#           - name: MYSQL_ROOT_PASSWORD
#             valueFrom:
#               secretKeyRef:
#                 name: mysql-pass
#                 key: password
#           ports:
#             - containerPort: 3306
#               name: mysql
#           volumeMounts:
#             - name: wordpress-sql
#               mountPath: /var/www/html
#       volumes:
#        - name: wordpress-sql
#          persistentVolumeClaim:
#            claimName: shared-pvc-wp-sql

apiVersion: v1
kind: Service
metadata:
  name: mysql-dev
spec:
  type: LoadBalancer
  ports:
  - port: 3306
  selector:
    app: mysql-dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mysql-dev
spec:
  selector:
    matchLabels:
      app: mysql-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-dev
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-dev
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql-dev
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
